[bumpver]
current_version = "0.1.4"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = true

[bumpver.file_patterns]
"setup.py" = [
    'version="{version}"',
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"kcontrol/__init__.py" = [
    '__version__ = "{version}"'
]
"fabfile.py" = [
    'version = "{version}"',
]
